export const SYSTEM_SUPPORTED_PAYMENT_METHODS_CREATED = 'SYSTEM_SUPPORTED_PAYMENT_METHODS_CREATED'
export const SYSTEM_SUPPORTED_PAYMENT_METHOD_ADDED = 'SYSTEM_SUPPORTED_PAYMENT_METHOD_ADDED'
export const SYSTEM_SUPPORTED_PAYMENT_METHOD_REMOVED = 'SYSTEM_SUPPORTED_PAYMENT_METHOD_REMOVED'

export const PERSON_CREATED = 'PERSON_CREATED'
export const PREFERRED_PAYMENT_METHOD_ASSIGNED = 'PREFERRED_PAYMENT_METHOD_ASSIGNED'
export const PERSON_DELETED = 'PERSON_DELETED'
